include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    public_member_api_docs: false
    library_private_types_in_public_api: false
    avoid_setters_without_getters: false
    avoid_dynamic_calls: false
    lines_longer_than_80_chars: false
